# Config wiki: https://github.com/crytic/echidna/wiki/Config

# testMode: mode to use while testing
# Available modes:
# - property: check properties, in this mode, the test function's name must start with 'echidna'
# - assertion: check assertions
# - exploration: explore the contract
# - optimization: optimize a property
testMode: "assertion"

# allContracts: if true, all contracts in the codebase will be considered main contracts for testing
# Default: false
# guide: https://secure-contracts.com/program-analysis/echidna/advanced/using-all-contracts.html
allContracts: false


# balanceContract: balance of deployed contract in wei
balanceContract: 99999999999999999999999
# Default: 0

# Directory to save corpus
# Default: null
# corpusDir: ".corpus"

# Number of test sequences to run
# Default: 50000
testLimit: 999999999999999999  # unlimited

deployer: "0x10000"

